import { Span } from 'types/api/trace/getTraceV2';

// TODO: Remove this mock data when the new span details API is available
export const mockSpan: Partial<Span> = {
	attributes_bool: {},
	attributes_number: {},
	attributes_string: {
		'code.filepath': '/home/ec2-user/tiny-coffee/tiny-coffee-v2/app.py',
		'code.function': 'checkout',
		item: 'espresso',
		result: 'success',
		description: 'Root span description',
		'service.name': 'testattrservice',
		timestamp: 'jksdhfkjsdf',
		trace_id: 'mytrace',
	},
	db_name: '',
	db_operation: '',
	external_http_method: '',
	external_http_url: '',
	http_host: '',
	http_method: '',
	http_url: '',
	is_remote: 'no',
	response_status_code: '',
	resources_string: {
		'cloud.account.id': 'signoz-staging',
		'cloud.availability_zone': 'us-central1-c',
		'cloud.platform': 'gcp_kubernetes_engine',
		'cloud.provider': 'gcp',
		'deployment.environment': 'mq-kafka',
		'host.arch': 'amd64',
		'host.id': '2704325070076130074',
		'host.name': 'gke-mgmt-pl-generator-e2st4-sp-41c1bdc8-b98q',
		'k8s.cluster.name': 'mgmt',
		'k8s.deployment.name': 'kafka-consumer-3',
		'k8s.namespace.name': 'generator',
		'k8s.node.name': 'gke-mgmt-pl-generator-e2st4-sp-41c1bdc8-b98q',
		'k8s.node.uid': 'f59295eb-1d51-417d-abbf-10bd25b87de2',
		'k8s.pod.ip': '10.32.5.6',
		'k8s.pod.name': 'kafka-consumer-3-df495d96f-c6kmv',
		'k8s.pod.start_time': '2026-03-22T11:34:20Z',
		'k8s.pod.uid': '7e50378b-e16b-4d78-b718-c58ac4a26e41',
		'os.description': 'Linux 6.6.113+',
		'os.type': 'linux',
		'process.command_args':
			'["/usr/local/openjdk-22/bin/java","-javaagent:/opt/opentelemetry-javaagent.jar","-Dotel.instrumentation.kafka.producer-propagation.enabled=true","-Dotel.instrumentation.kafka.experimental-span-attributes=true","-Dotel.instrumentation.kafka.metric-reporter.enabled=true","-jar","/opt/kafka-consumer.jar"]',
		'process.executable.path': '/usr/local/openjdk-22/bin/java',
		'process.pid': '1',
		'process.runtime.description':
			'Oracle Corporation OpenJDK 64-Bit Server VM 22+36-2370',
		'process.runtime.name': 'OpenJDK Runtime Environment',
		'process.runtime.version': '22+36-2370',
		'service.instance.id': '308b9f4c-5848-467f-b66f-dd5d4f2fbb39',
		'service.name': 'consumer-svc-3',
		'signoz.workspace.key.id': '019855ca-7622-787e-8fc1-8e8a38a06b0e',
		'telemetry.distro.name': 'opentelemetry-java-instrumentation',
		'telemetry.distro.version': '2.4.0',
		'telemetry.sdk.language': 'java',
		'telemetry.sdk.name': 'opentelemetry',
		'telemetry.sdk.version': '1.38.0',
	},
};
