package markdownrenderer

import (
	"context"
	"log/slog"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

var (
	testMarkdown = `# 🔥 FIRING: High CPU Usage on api-gateway

https://signoz.example.com/alerts/123
https://runbooks.example.com/cpu-high

## Alert Details

**Status:** **FIRING** | *api-gateway* service is experiencing high CPU usage. ~~resolved~~ previously.

Alert triggered because ` + "`cpu_usage_percent`" + ` exceeded threshold ` + "`90`" + `.

[View Alert in SigNoz](https://signoz.example.com/alerts/123) | [View Logs](https://signoz.example.com/logs?service=api-gateway) | [View Traces](https://signoz.example.com/traces?service=api-gateway)

![critical](https://signoz.example.com/badges/critical.svg "Critical Alert")

## Alert Labels

| Label    | Value       |
| -------- | ----------- |
| service  | api-gateway |
| instance | pod-5a8b3c  |
| severity | critical    |
| region   | us-east-1   |

## Remediation Steps

1. Check current CPU usage on the pod
2. Review recent deployments for regressions
3. Scale horizontally if load-related
    1. Increase replica count
    2. Verify HPA configuration

## Affected Services

* api-gateway
* auth-service
* payment-service
    * payment-processor
    * payment-validator

## Incident Checklist

- [x] Alert acknowledged
- [x] On-call notified
- [ ] Root cause identified
- [ ] Fix deployed

## Alert Rule Description

> This alert fires when CPU usage exceeds 90% for more than 5 minutes on any pod in the api-gateway service.
>
>> For capacity planning guidelines, see the infrastructure runbook section on horizontal pod autoscaling.

## Triggered Query
` + "```promql\navg(rate(container_cpu_usage_seconds_total{service=\"api-gateway\"}[5m])) by (pod) > 0.9\n```" + `

## Inline Details

This alert was generated by SigNoz using ` + "`alertmanager`" + ` rules engine.
`
)

func newTestRenderer() MarkdownRenderer {
	return NewMarkdownRenderer(slog.New(slog.NewTextHandler(os.Stdout, nil)))
}

func TestRenderHTML_Composite(t *testing.T) {
	renderer := newTestRenderer()

	html, err := renderer.Render(context.Background(), testMarkdown, MarkdownFormatHTML)
	require.NoError(t, err)

	// Full expected output for exact match
	expected := `<h1>🔥 FIRING: High CPU Usage on api-gateway</h1><p></p>` +
		`<p><a href="https://signoz.example.com/alerts/123">https://signoz.example.com/alerts/123</a><p></p><a href="https://runbooks.example.com/cpu-high">https://runbooks.example.com/cpu-high</a></p><p></p>` +
		`<h2>Alert Details</h2><p></p>` +
		`<p><strong>Status:</strong> <strong>FIRING</strong> | <em>api-gateway</em> service is experiencing high CPU usage. <del>resolved</del> previously.</p><p></p>` +
		`<p>Alert triggered because <code>cpu_usage_percent</code> exceeded threshold <code>90</code>.</p><p></p>` +
		`<p><a href="https://signoz.example.com/alerts/123">View Alert in SigNoz</a> | <a href="https://signoz.example.com/logs?service=api-gateway">View Logs</a> | <a href="https://signoz.example.com/traces?service=api-gateway">View Traces</a></p><p></p>` +
		`<p><img src="https://signoz.example.com/badges/critical.svg" alt="critical" title="Critical Alert"></p><p></p>` +
		`<h2>Alert Labels</h2><p></p>` +
		`<table><p></p><thead><p></p><tr><p></p><th>Label</th><p></p><th>Value</th><p></p></tr><p></p></thead><p></p>` +
		`<tbody><p></p><tr><p></p><td>service</td><p></p><td>api-gateway</td><p></p></tr><p></p>` +
		`<tr><p></p><td>instance</td><p></p><td>pod-5a8b3c</td><p></p></tr><p></p>` +
		`<tr><p></p><td>severity</td><p></p><td>critical</td><p></p></tr><p></p>` +
		`<tr><p></p><td>region</td><p></p><td>us-east-1</td><p></p></tr><p></p></tbody><p></p></table><p></p>` +
		`<h2>Remediation Steps</h2><p></p>` +
		`<ol><p></p><li>Check current CPU usage on the pod</li><p></p><li>Review recent deployments for regressions</li><p></p><li>Scale horizontally if load-related<p></p>` +
		`<ol><p></p><li>Increase replica count</li><p></p><li>Verify HPA configuration</li><p></p></ol><p></p></li><p></p></ol><p></p>` +
		`<h2>Affected Services</h2><p></p>` +
		`<ul><p></p><li>api-gateway</li><p></p><li>auth-service</li><p></p><li>payment-service<p></p>` +
		`<ul><p></p><li>payment-processor</li><p></p><li>payment-validator</li><p></p></ul><p></p></li><p></p></ul><p></p>` +
		`<h2>Incident Checklist</h2><p></p>` +
		`<ul><p></p><li><input checked="" disabled="" type="checkbox"> Alert acknowledged</li><p></p>` +
		`<li><input checked="" disabled="" type="checkbox"> On-call notified</li><p></p>` +
		`<li><input disabled="" type="checkbox"> Root cause identified</li><p></p>` +
		`<li><input disabled="" type="checkbox"> Fix deployed</li><p></p></ul><p></p>` +
		`<h2>Alert Rule Description</h2><p></p>` +
		`<blockquote><p></p><p>This alert fires when CPU usage exceeds 90% for more than 5 minutes on any pod in the api-gateway service.</p><p></p>` +
		`<blockquote><p></p><p>For capacity planning guidelines, see the infrastructure runbook section on horizontal pod autoscaling.</p><p></p></blockquote><p></p></blockquote><p></p>` +
		`<h2>Triggered Query</h2><p></p>` +
		`<pre><code class="language-promql">avg(rate(container_cpu_usage_seconds_total{service=&quot;api-gateway&quot;}[5m])) by (pod) &gt; 0.9<p></p></code></pre><p></p>` +
		`<h2>Inline Details</h2><p></p>` +
		`<p>This alert was generated by SigNoz using <code>alertmanager</code> rules engine.</p><p></p>`

	assert.Equal(t, expected, html)
}

func TestRenderHTML_InlineFormatting(t *testing.T) {
	renderer := newTestRenderer()

	input := `# 🔥 FIRING: High CPU on api-gateway
## Alert Status

**FIRING** alert for *api-gateway* service — ~~resolved~~ previously.

Metric ` + "`cpu_usage_percent`" + ` exceeded threshold. [View in SigNoz](https://signoz.example.com/alerts/123)

![critical](https://signoz.example.com/badges/critical.svg "Critical Alert")`

	html, err := renderer.Render(context.Background(), input, MarkdownFormatHTML)
	require.NoError(t, err)

	expected := `<h1>🔥 FIRING: High CPU on api-gateway</h1><p></p><h2>Alert Status</h2><p></p>` +
		`<p><strong>FIRING</strong> alert for <em>api-gateway</em> service — <del>resolved</del> previously.</p><p></p>` +
		`<p>Metric <code>cpu_usage_percent</code> exceeded threshold. <a href="https://signoz.example.com/alerts/123">View in SigNoz</a></p><p></p>` +
		`<p><img src="https://signoz.example.com/badges/critical.svg" alt="critical" title="Critical Alert"></p><p></p>`

	assert.Equal(t, expected, html)
}

func TestRenderHTML_BlockElements(t *testing.T) {
	renderer := newTestRenderer()

	input := `1. Check CPU usage on the pod
2. Review recent deployments
3. Scale horizontally if needed

* api-gateway
* auth-service
* payment-service

- [x] Alert acknowledged
- [ ] Root cause identified

> This alert fires when CPU usage exceeds 90% for more than 5 minutes.

| Label    | Value       |
| -------- | ----------- |
| service  | api-gateway |
| severity | critical    |

` + "```promql\navg(rate(container_cpu_usage_seconds_total{service=\"api-gateway\"}[5m])) by (pod) > 0.9\n```"

	html, err := renderer.Render(context.Background(), input, MarkdownFormatHTML)
	require.NoError(t, err)

	expected := `<ol><p></p><li>Check CPU usage on the pod</li><p></p><li>Review recent deployments</li><p></p><li>Scale horizontally if needed</li><p></p></ol><p></p>` +
		`<ul><p></p><li>api-gateway</li><p></p><li>auth-service</li><p></p><li>payment-service</li><p></p></ul><p></p>` +
		`<ul><p></p><li><input checked="" disabled="" type="checkbox"> Alert acknowledged</li><p></p>` +
		`<li><input disabled="" type="checkbox"> Root cause identified</li><p></p></ul><p></p>` +
		`<blockquote><p></p><p>This alert fires when CPU usage exceeds 90% for more than 5 minutes.</p><p></p></blockquote><p></p>` +
		`<table><p></p><thead><p></p><tr><p></p><th>Label</th><p></p><th>Value</th><p></p></tr><p></p></thead><p></p>` +
		`<tbody><p></p><tr><p></p><td>service</td><p></p><td>api-gateway</td><p></p></tr><p></p>` +
		`<tr><p></p><td>severity</td><p></p><td>critical</td><p></p></tr><p></p></tbody><p></p></table><p></p>` +
		`<pre><code class="language-promql">avg(rate(container_cpu_usage_seconds_total{service=&quot;api-gateway&quot;}[5m])) by (pod) &gt; 0.9<p></p></code></pre><p></p>`

	assert.Equal(t, expected, html)
}
